-- FLUS 4.1.1 - conciliacion de cobros, comisiones e impuestos Mercado Pago.

CREATE TABLE IF NOT EXISTS `mercadopago_liquidaciones` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `environment` varchar(20) NOT NULL,
  `source` varchar(20) NOT NULL DEFAULT 'payment_api',
  `venta_id` int(11) DEFAULT NULL,
  `venta_pago_id` int(11) DEFAULT NULL,
  `payment_id` varchar(100) NOT NULL,
  `order_id` varchar(100) DEFAULT NULL,
  `external_reference` varchar(255) DEFAULT NULL,
  `status` varchar(40) DEFAULT NULL,
  `status_detail` varchar(100) DEFAULT NULL,
  `transaction_type` varchar(40) NOT NULL DEFAULT 'SETTLEMENT',
  `currency_id` varchar(10) NOT NULL DEFAULT 'ARS',
  `transaction_amount` decimal(14,2) NOT NULL DEFAULT 0.00,
  `fee_amount` decimal(14,2) NOT NULL DEFAULT 0.00,
  `taxes_amount` decimal(14,2) NOT NULL DEFAULT 0.00,
  `refunded_amount` decimal(14,2) NOT NULL DEFAULT 0.00,
  `net_received_amount` decimal(14,2) NOT NULL DEFAULT 0.00,
  `payment_method_id` varchar(50) DEFAULT NULL,
  `payment_type_id` varchar(50) DEFAULT NULL,
  `date_created` datetime DEFAULT NULL,
  `date_approved` datetime DEFAULT NULL,
  `money_release_date` datetime DEFAULT NULL,
  `fee_json` longtext DEFAULT NULL,
  `taxes_json` longtext DEFAULT NULL,
  `raw_json` longtext DEFAULT NULL,
  `sync_error` varchar(500) DEFAULT NULL,
  `last_synced_at` datetime NOT NULL DEFAULT current_timestamp(),
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_mp_liquidacion_environment_payment` (`environment`,`payment_id`),
  KEY `idx_mp_liquidacion_venta` (`venta_id`),
  KEY `idx_mp_liquidacion_venta_pago` (`venta_pago_id`),
  KEY `idx_mp_liquidacion_fecha` (`date_approved`),
  KEY `idx_mp_liquidacion_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
